import { v, ConvexError } from "convex/values"
import { mutation, internalQuery } from "./_generated/server"
import type { MutationCtx, QueryCtx } from "./_generated/server"
import type { Id } from "./_generated/dataModel"
import { requireIdentity, lookupAdmin, lookupStudent, requireStudentForWrite } from "./lib/auth"

// Document upload and authorized serving for both wizards, replacing
// /api/upload and /api/upload/spotlight.
//
// ─────────────────────────────────────────────────────────────────────────────
// NOTHING HERE MINTS A URL. That is the Phase 4 decision, made deliberately.
//
// ctx.storage.getUrl() returns a URL with no expiry whose only invalidation is
// deleting the object — the installed types say it outright: "Once a file is
// deleted, any URLs previously generated by getUrl will return 404s." Anyone
// who ever sees the string can fetch the file forever, and it leaks through
// browser history, server logs, Referer headers and forwarded links. These are
// Aadhaar cards and bank passbooks.
//
// So private documents are served by an authorized HTTP action (convex/http.ts)
// that re-checks the caller on every request, over authorizeDownload below.
// Public spotlight photos keep plain getUrl() in featured.ts and admin.ts —
// those are published on the homepage by design, so a permanent URL costs
// nothing.
// ─────────────────────────────────────────────────────────────────────────────
//
// The shape of the flow changes from the Supabase version. There, the file was
// POSTed to a Next route which validated it and then streamed it to storage, so
// the server saw the bytes before they landed. Convex hands the client a short-
// lived upload URL and the client POSTs to storage directly, so by the time any
// function runs, the file is already stored.
//
// That moves validation after the fact, which is why the checks below read the
// _storage system table rather than trusting the arguments. The client's claimed
// size and content type are not used for anything: `size` and `contentType` come
// from what Convex actually received. A client that lies about a 40MB video
// being a 2MB JPEG gets rejected on the real numbers, and the stored object is
// deleted on the way out rather than left orphaned.

const MAX_FILE_SIZE = 10 * 1024 * 1024 // 10MB

// The old route validated against this list but its rejection message said
// "5MB limit" while the constant was 10MB. The list is carried over as-is; the
// message is fixed below.
const ALLOWED_MIME_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
  "application/pdf",
]

const applicationDocumentType = v.union(
  v.literal("student_photo"),
  v.literal("ssc_marksheet"),
  v.literal("aadhar_student"),
  v.literal("aadhar_parent"),
  v.literal("bonafide_certificate"),
  v.literal("bank_passbook"),
  v.literal("first_year_marksheet"),
  v.literal("mango_plant_photo"),
)

const spotlightDocumentType = v.union(
  v.literal("photo"),
  v.literal("marksheet"),
  v.literal("aadhar"),
  v.literal("income_certificate"),
  v.literal("other"),
)

// Authenticated: an upload URL is a write capability against our storage, so it
// is not handed to anonymous callers. Any signed-in student may request one —
// which document it ends up attached to is decided (and ownership-checked) by
// the attach mutations below, not here.
export const generateUploadUrl = mutation({
  args: {},
  handler: async (ctx) => {
    await requireStudentForWrite(ctx)
    return await ctx.storage.generateUploadUrl()
  },
})

// Reads the authoritative metadata Convex recorded for the stored object and
// enforces the limits against it.
//
// ─────────────────────────────────────────────────────────────────────────────
// IT DOES NOT DELETE THE REJECTED OBJECT, AND MUST NOT. TWO SEPARATE REASONS.
//
// 1. It would not work. A Convex mutation is a transaction: `storage.delete()`
//    followed by `throw` rolls the delete back with everything else, so the
//    object survives anyway. This was verified against the deployment, not
//    reasoned about — an earlier version of this file did exactly that and the
//    orphaned file was still in `_storage` afterwards.
//
// 2. Making it work would be worse than the leak. The storageId is a client
//    argument, and `_storage` records no uploader, so this function cannot tell
//    "the file the caller just uploaded" from "any storageId the caller typed".
//    A delete that survived would therefore hand every authenticated student a
//    way to destroy another student's file: attach it to an application they do
//    own, fail validation on purpose, and the object is gone. For Aadhaar cards
//    and bank passbooks that is a considerably worse outcome than some wasted
//    bytes.
//
// Orphans are swept instead, by age and by reachability, in maintenance.ts.
// The only storage delete anywhere in this file is of a superseded id read out
// of our OWN document row, which is not client-supplied and is safe.
// ─────────────────────────────────────────────────────────────────────────────
async function validateStoredFile(
  ctx: MutationCtx,
  storageId: Id<"_storage">,
): Promise<{ size: number; contentType: string }> {
  const meta = await ctx.db.system.get("_storage", storageId)
  if (!meta) {
    throw new ConvexError("Uploaded file not found")
  }

  const contentType = meta.contentType ?? ""
  if (!ALLOWED_MIME_TYPES.includes(contentType)) {
    throw new ConvexError("Invalid file type. Allowed: JPEG, PNG, WebP, PDF")
  }
  if (meta.size > MAX_FILE_SIZE) {
    throw new ConvexError("File size exceeds the 10MB limit")
  }

  return { size: meta.size, contentType }
}

export const attachApplicationDocument = mutation({
  args: {
    applicationId: v.id("applications"),
    documentType: applicationDocumentType,
    storageId: v.id("_storage"),
    fileName: v.string(),
  },
  handler: async (ctx, args) => {
    const student = await requireStudentForWrite(ctx)

    const application = await ctx.db.get("applications", args.applicationId)
    if (!application || application.studentId !== student._id) {
      // No cleanup here either, and for the sharper half of the reason above:
      // on this path the caller has NOT proven anything about the storageId,
      // so deleting it is exactly the arbitrary-deletion primitive described
      // in validateStoredFile. Throw, and let the sweeper handle the bytes.
      throw new ConvexError("Application not found")
    }

    const { size, contentType } = await validateStoredFile(ctx, args.storageId)

    // One document per type per application, matching the Supabase route: a
    // re-upload replaces rather than accumulates, and the superseded object is
    // deleted from storage in the same transaction as the row that pointed at
    // it. Doing the delete first would orphan the row if the patch then failed.
    const existing = await ctx.db
      .query("applicationDocuments")
      .withIndex("by_applicationId_and_documentType", (q) =>
        q
          .eq("applicationId", args.applicationId)
          .eq("documentType", args.documentType),
      )
      .unique()

    if (existing) {
      const supersededStorageId = existing.storageId
      await ctx.db.patch("applicationDocuments", existing._id, {
        storageId: args.storageId,
        fileName: args.fileName,
        fileSize: size,
        mimeType: contentType,
      })
      if (supersededStorageId !== args.storageId) {
        await ctx.storage.delete(supersededStorageId)
      }
      return existing._id
    }

    return await ctx.db.insert("applicationDocuments", {
      applicationId: args.applicationId,
      documentType: args.documentType,
      storageId: args.storageId,
      fileName: args.fileName,
      fileSize: size,
      mimeType: contentType,
    })
  },
})

export const attachSpotlightDocument = mutation({
  args: {
    spotlightApplicationId: v.id("spotlightApplications"),
    documentType: spotlightDocumentType,
    storageId: v.id("_storage"),
    fileName: v.string(),
  },
  handler: async (ctx, args) => {
    const student = await requireStudentForWrite(ctx)

    const application = await ctx.db.get(
      "spotlightApplications",
      args.spotlightApplicationId,
    )
    if (!application || application.studentId !== student._id) {
      throw new ConvexError("Spotlight application not found")
    }

    const { size, contentType } = await validateStoredFile(ctx, args.storageId)

    // "other" is the one type a student may legitimately attach more than once,
    // so it appends instead of replacing. Every other type is singular and
    // replaces, exactly as on the scholarship side.
    if (args.documentType !== "other") {
      const existing = await ctx.db
        .query("spotlightDocuments")
        .withIndex("by_spotlightApplicationId_and_documentType", (q) =>
          q
            .eq("spotlightApplicationId", args.spotlightApplicationId)
            .eq("documentType", args.documentType),
        )
        .unique()

      if (existing) {
        const supersededStorageId = existing.storageId
        await ctx.db.patch("spotlightDocuments", existing._id, {
          storageId: args.storageId,
          fileName: args.fileName,
          fileSize: size,
          mimeType: contentType,
        })
        if (supersededStorageId !== args.storageId) {
          await ctx.storage.delete(supersededStorageId)
        }
        return existing._id
      }
    }

    return await ctx.db.insert("spotlightDocuments", {
      spotlightApplicationId: args.spotlightApplicationId,
      documentType: args.documentType,
      storageId: args.storageId,
      fileName: args.fileName,
      fileSize: size,
      mimeType: contentType,
    })
  },
})

// -- serving ----------------------------------------------------------------

type ResolvedDocument = {
  storageId: Id<"_storage">
  fileName: string
  mimeType: string
  ownerStudentId: Id<"students">
}

// Both tables are the same shape for this purpose — a storageId plus a parent
// row carrying studentId — but the ids are table-scoped, so each needs its own
// resolver. normalizeId is what makes a garbage path segment a clean null
// rather than a thrown validation error.

async function resolveApplicationDocument(
  ctx: QueryCtx,
  documentId: string,
): Promise<ResolvedDocument | null> {
  const docId = ctx.db.normalizeId("applicationDocuments", documentId)
  if (!docId) return null

  const doc = await ctx.db.get("applicationDocuments", docId)
  if (!doc) return null

  const parent = await ctx.db.get("applications", doc.applicationId)
  if (!parent) return null

  return {
    storageId: doc.storageId,
    fileName: doc.fileName,
    mimeType: doc.mimeType,
    ownerStudentId: parent.studentId,
  }
}

async function resolveSpotlightDocument(
  ctx: QueryCtx,
  documentId: string,
): Promise<ResolvedDocument | null> {
  const docId = ctx.db.normalizeId("spotlightDocuments", documentId)
  if (!docId) return null

  const doc = await ctx.db.get("spotlightDocuments", docId)
  if (!doc) return null

  const parent = await ctx.db.get(
    "spotlightApplications",
    doc.spotlightApplicationId,
  )
  if (!parent) return null

  return {
    storageId: doc.storageId,
    fileName: doc.fileName,
    mimeType: doc.mimeType,
    ownerStudentId: parent.studentId,
  }
}

// internalQuery, not query: this is reachable only from our own functions and
// never from the internet. The HTTP action in http.ts verifies the caller's
// identity before calling it, and the identity checked in here is this call's
// own ctx.auth — never anything passed in as an argument.
export const authorizeDownload = internalQuery({
  args: {
    kind: v.union(v.literal("application"), v.literal("spotlight")),
    // v.string(), not v.id(): the value arrives as a URL path segment, so a
    // malformed one has to become a 404 rather than an ArgumentValidationError
    // surfacing to the caller as a 500.
    documentId: v.string(),
  },
  handler: async (ctx, args): Promise<ResolvedDocument | null> => {
    // Throws "Not authenticated" if ctx.auth is empty. The HTTP action already
    // rejects anonymous callers before reaching this, so getting here without
    // an identity means auth did not survive the runQuery hop — a failure worth
    // surfacing loudly rather than degrading into a 404.
    const identity = await requireIdentity(ctx)

    const resolved =
      args.kind === "application"
        ? await resolveApplicationDocument(ctx, args.documentId)
        : await resolveSpotlightDocument(ctx, args.documentId)
    if (!resolved) return null

    // Admins may read any applicant's documents — that is the entire point of
    // the review screens. lookupAdmin rather than requireAdmin, so a non-admin
    // falls through to the ownership check instead of throwing.
    const admin = await lookupAdmin(ctx, identity)
    if (!admin) {
      const student = await lookupStudent(ctx, identity)
      // Not-a-student, no-such-document and not-yours all collapse into the
      // same null, so the route answers 404 to every one of them and nobody can
      // use it to learn which document ids exist. Same reasoning as the detail
      // queries in admin.ts and studentData.ts.
      if (!student || student._id !== resolved.ownerStudentId) return null
    }

    return resolved
  },
})
