import nextCoreWebVitals from "eslint-config-next/core-web-vitals"
import nextTypescript from "eslint-config-next/typescript"

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "convex/_generated/**", // generated by `convex dev`
      ".history/**", // editor local history
      ".agents/**", // installed agent skills
      "agent/**", // duplicate skill copy from `convex ai-files install`
      "next-env.d.ts",
      "scripts/**",
    ],
  },

  ...nextCoreWebVitals,
  ...nextTypescript,

  {
    rules: {
      // TEMPORARY — restore to "error" after Phase 2 of CONVEX_MIGRATION_PLAN.md.
      //
      // 24 instances today, but ~13 are the useEffect + fetch + setState pattern
      // in app/admin/* and app/dashboard/* that useQuery/usePreloadedQuery
      // deletes outright. Fixing those now is throwaway work, and leaving them
      // as errors means `npm run lint` fails on day one — which trains everyone
      // to ignore the whole command. Warn keeps them visible without that.
      //
      // The genuine remainder (AnimatedInput, AnimatedTextarea, HeroSlider,
      // MainNavigation) is UI state, not data fetching, and should be fixed
      // properly when the rule goes back to error.
      "react-hooks/set-state-in-effect": "warn",

      // Two instances, both pragmatic rather than buggy:
      //   ApplicationWizard.tsx:250 — `student.gender as any` narrows a nullable
      //     DB string to the form union. Convex's typed union removes the need
      //     in Phase 3, so this resolves itself.
      //   ApplicationWizard.tsx:341 — `trigger(fields as any)` is react-hook-form
      //     dynamic-field-array friction with no clean typing.
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },

  {
    // Vendored shadcn/ui components. Regenerated by `npx shadcn add`, so local
    // patches are lost on any re-add — not worth hand-maintaining. Downgraded,
    // not disabled, so genuine problems still surface.
    files: ["components/ui/**"],
    rules: {
      "react-hooks/purity": "warn",
      "react-hooks/incompatible-library": "warn",
      "@typescript-eslint/no-unused-vars": "warn",
    },
  },
]

export default config
